// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repository;

#nullable disable

namespace catalog.Migrations
{
    [DbContext(typeof(repositoryContext))]
    [Migration("20241108222358_wer")]
    partial class wer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.models.curtains", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.Property<string>("matherial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<double>("width")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Curtains");

                    b.HasData(
                        new
                        {
                            id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/76584172-fb7e-11ec-80d9-002590843481_1.jpg",
                            color = "Бежевый",
                            description = "Портьера велюр Марсель — это элегантные шторы из высококачественного велюра, идеально подходящие для создания уютной атмосферы в вашем доме. Шторы прекрасно блокируют свет и сохраняют тепло.",
                            height = 150.0,
                            matherial = "Велюр",
                            name = "Портьера велюр Марсель",
                            price = 3000.0,
                            width = 260.0
                        },
                        new
                        {
                            id = new Guid("a1d4c053-49b6-410c-bc78-2d54a9991871"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_gura_azul_548_015_interior.jpg",
                            color = "Бежевый",
                            description = "Шторы Neula сочетают в себе современный дизайн и высокую функциональность. Эти бежевые шторы добавят стильный акцент вашему интерьеру, блокируя яркий свет.",
                            height = 160.0,
                            matherial = "Лен",
                            name = "Шторы Neula",
                            price = 3500.0,
                            width = 270.0
                        },
                        new
                        {
                            id = new Guid("b2d4c053-49b6-410c-bc78-2d54a9991872"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_gura_fango_548_060_interior.jpg",
                            color = "Зеленый",
                            description = "Шторы Dubley — это стильное решение для вашего интерьера. Они прекрасно смотрятся в любом помещении и создают атмосферу уюта и комфорта.",
                            height = 150.0,
                            matherial = "Хлопок",
                            name = "Шторы Dubley",
                            price = 2800.0,
                            width = 250.0
                        },
                        new
                        {
                            id = new Guid("c3d4c053-49b6-410c-bc78-2d54a9991873"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_neula_beige_interior.jpg",
                            color = "Серый",
                            description = "Эти серые шторы Neula обеспечивают отличную изоляцию от света и шума, а также добавляют элегантность в любое помещение.",
                            height = 160.0,
                            matherial = "Вискоза",
                            name = "Шторы Neula",
                            price = 4000.0,
                            width = 280.0
                        },
                        new
                        {
                            id = new Guid("d4d4c053-49b6-410c-bc78-2d54a9991874"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_neula_gris_549_070_interior.jpg",
                            color = "Серый",
                            description = "Шторы Gura привнесут утонченность и стиль в ваш дом. Они идеально подойдут для гостиной или спальни.",
                            height = 140.0,
                            matherial = "Полиэстер",
                            name = "Шторы Gura",
                            price = 3200.0,
                            width = 270.0
                        },
                        new
                        {
                            id = new Guid("e5d4c053-49b6-410c-bc78-2d54a9991875"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtori_dubley_verde_546_080_interior.jpg",
                            color = "Кофе с молоком",
                            description = "Элегантные шторы Gura в цвете кофе с молоком — идеальное решение для тех, кто ценит тепло и уют в интерьере.",
                            height = 150.0,
                            matherial = "Вискоза",
                            name = "Шторы Gura",
                            price = 3000.0,
                            width = 260.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
