// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using repository;

#nullable disable

namespace catalog.Migrations
{
    [DbContext(typeof(repositoryContext))]
    partial class repositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.models.curtains", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.Property<string>("matherial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<double>("width")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Curtains");

                    b.HasData(
                        new
                        {
                            id = new Guid("ef18a7a3-48b5-40f3-887f-c0a9615addbe"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/76584172-fb7e-11ec-80d9-002590843481_1.jpg",
                            color = "Бежевый",
                            description = "Портьера велюр Марсель — это элегантные шторы из высококачественного велюра, идеально подходящие для создания уютной атмосферы в вашем доме. Шторы прекрасно блокируют свет и сохраняют тепло.",
                            height = 150.0,
                            matherial = "Велюр",
                            name = "Портьера велюр Марсель",
                            price = 5200.0,
                            width = 260.0
                        },
                        new
                        {
                            id = new Guid("6ddb5d52-2b97-43c4-b664-8849b00e6949"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_gura_azul_548_015_interior.jpg",
                            color = "Бежевый",
                            description = "Шторы Neula сочетают в себе современный дизайн и высокую функциональность. Эти бежевые шторы добавят стильный акцент вашему интерьеру, блокируя яркий свет.",
                            height = 160.0,
                            matherial = "Лен",
                            name = "Шторы Neula",
                            price = 3500.0,
                            width = 270.0
                        },
                        new
                        {
                            id = new Guid("eb58c14f-e07f-4e01-ad45-6efb4802b3bb"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_gura_fango_548_060_interior.jpg",
                            color = "Зеленый",
                            description = "Шторы Dubley — это стильное решение для вашего интерьера. Они прекрасно смотрятся в любом помещении и создают атмосферу уюта и комфорта.",
                            height = 150.0,
                            matherial = "Хлопок",
                            name = "Шторы Dubley",
                            price = 2800.0,
                            width = 250.0
                        },
                        new
                        {
                            id = new Guid("1c0e42c9-3676-4c49-8f16-e7c1d8ad8ba0"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_neula_beige_interior.jpg",
                            color = "Серый",
                            description = "Эти серые шторы Neula обеспечивают отличную изоляцию от света и шума, а также добавляют элегантность в любое помещение.",
                            height = 160.0,
                            matherial = "Вискоза",
                            name = "Шторы Neula2",
                            price = 4000.0,
                            width = 280.0
                        },
                        new
                        {
                            id = new Guid("6f5326f6-3f5a-4d4a-b3c6-969dbbde638a"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtora_neula_gris_549_070_interior.jpg",
                            color = "Серый",
                            description = "Шторы Gura привнесут утонченность и стиль в ваш дом. Они идеально подойдут для гостиной или спальни.",
                            height = 140.0,
                            matherial = "Полиэстер",
                            name = "Шторы Gura",
                            price = 3200.0,
                            width = 270.0
                        },
                        new
                        {
                            id = new Guid("33acdeeb-676e-46b3-a39b-a101f8443d87"),
                            ImageUrl = "https://storage.yandexcloud.net/web-cterx/delfa_shtori_dubley_verde_546_080_interior.jpg",
                            color = "Кофе с молоком",
                            description = "Элегантные шторы Gura в цвете кофе с молоком — идеальное решение для тех, кто ценит тепло и уют в интерьере.",
                            height = 150.0,
                            matherial = "Вискоза",
                            name = "Шторы Gura2",
                            price = 3100.0,
                            width = 260.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
